name: generate plantuml
on:
  push:
    branches:
      - master
jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 10
    - name: plantuml
      id: plantuml
      uses: rolfmadsen/generate-plantuml-action@master
      with:
        path: docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}